---
title: "Feature selection on MNIST data"
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(dplyr)
```

```{r data}
set.seed(123)

library(celavi)
library(dplyr)
library(klassets)

use_small_data <- TRUE

data <- klassets::mnist_train
data <- dplyr::mutate(data, label = factor(label))

test <- klassets::mnist_test
test <- dplyr::mutate(test, label = factor(label))

iter  <- 20
frac <- .25

if(use_small_data){
  
  data <- dplyr::sample_n(data, 10000)
  data <- dplyr::select(data, c(1, sample(2:785, 500)))  
  test <- dplyr::sample_n(test, 1000)
  
  iter <- 20
  frac <- 1/10
  
} 
```


```{r procedure}
x <- feature_selection(
  ranger::ranger,
  data = data,
  test = test,
  response = "label",
  # stat = function(x) quantile(x, .25),
  stat = function(x) quantile(x, .75),
  iterations = iter,
  sample_frac = frac,
  predict_function = function(object, newdata){ranger:::predict.ranger(object, data = newdata)$predictions},
  parallel = FALSE,
  max.depth = 15
)

x

plot(x)
```


